### ISSUE TITLE
Cannot build libmbd

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/classic-flang-llvm-project#177] opened 2024-03-19 15:27 UTC
A regression has been encountered after the 2693fbaff2a67ccb64d8e6800e8d63cfc8180a4f commit when trying to compile libmbd (seehttps://github.com/libmbd/libmbd ):

```
[ 60%] Building Fortran object src/CMakeFiles/mbd.dir/mbd_methods.F90.o
cd src && flang -Dmbd_EXPORTS -Isrc -g -fPIC -c src/mbd_methods.F90 -o CMakeFiles/mbd.dir/mbd_methods.F90.o
Lowering Error: symbol freq$sd is an inconsistent array descriptor
Lowering Error: symbol freq$sd is an inconsistent array descriptor
F90-F-0000-Internal compiler error. Errors in Lowering       2  (src/mbd_methods.F90: 154)
F90/aarch64 Linux Flang F90  - 1.5 2017-05-01: compilation aborted
```

**Comment by bryanpkc** [comment] 2024-04-17 14:00
Duplicate of flang-compiler/flang#1442.

**Closed as completed by bryanpkc** 2024-04-17 14:00 UTC

**Comment by pawosm-arm** [comment] 2024-04-17 14:46
Seems I've opened it in a wrong repo!
